### ISSUE TITLE
 How to get the dataset?

### ISSUE THREAD

**Issue by MENGM0** [shenhaibb/SWDet#1]

**Comment by shenhaibb** [comment]
Thank you for your attention to our work, which has been published on [JSTARS](https://ieeexplore.ieee.org/document/9935119).
The SWAD dataset is available at www.kaggle.com/shenhaibb/swad-dataset.

**Comment by MENGM0** [comment]
thank you very much!

**Comment by MENGM0** [comment]
方便留个联系方式吗，qq: 303514180
